// registry/types.go
package registry

import (
	"encoding/json"
	"fmt"
)

// AddOn is one entry in the add-on EOL/compatibility registry (schema_version 2).
type AddOn struct {
	SchemaVersion int      `json:"schema_version" yaml:"schema_version"` // 2
	ID            string   `json:"id" yaml:"id"`
	DisplayName   string   `json:"display_name" yaml:"display_name"`
	Matchers      Matchers `json:"matchers" yaml:"matchers"`
	// Support is the product-level verdict. status "eol" is reserved for a
	// whole product that upstream retired (ingress-nginx); per-version end of
	// life lives in Cycles.
	Support Support `json:"support" yaml:"support"`
	// Cycles are the add-on's release lines, keyed on the APP version (never
	// a Helm chart version), newest first. Entries with endoflife_product
	// have them generated by tools/eol-sync.
	Cycles         []Cycle  `json:"cycles,omitempty" yaml:"cycles,omitempty"`
	Compat         []Compat `json:"compat,omitempty" yaml:"compat,omitempty"`
	Recommendation string   `json:"recommendation,omitempty" yaml:"recommendation,omitempty"`

	// EndoflifeProduct, when set, is the endoflife.date product slug for
	// this add-on (https://endoflife.date/api/<slug>.json). Entries that
	// carry it have Cycles kept in sync by tools/eol-sync; hand-curated
	// entries leave it empty.
	EndoflifeProduct string `json:"endoflife_product,omitempty" yaml:"endoflife_product,omitempty"`
}

type Matchers struct {
	// Images are repository paths without the registry host, matched as a
	// suffix on whole path segments: "ingress-nginx/controller" matches
	// registry.k8s.io/ingress-nginx/controller, k8s.gcr.io/ingress-nginx/controller
	// and mirror/ingress-nginx/controller. The version is read from the tag.
	// They never match a provider build (ProviderBuildPrefixes); an entry
	// for one names it with its host instead.
	Images []string `json:"images,omitempty" yaml:"images,omitempty"`
	Charts []string `json:"charts,omitempty" yaml:"charts,omitempty"` // exact chart name; version = the release's appVersion
	// Runtimes are node container runtime names, the scheme of
	// node.status.nodeInfo.containerRuntimeVersion ("containerd" in
	// "containerd://1.7.27").
	Runtimes []string `json:"runtimes,omitempty" yaml:"runtimes,omitempty"`
}

type Support struct {
	Status    string   `json:"status" yaml:"status"`                         // "supported" | "eol" | "unknown"
	EOLDate   string   `json:"eol_date,omitempty" yaml:"eol_date,omitempty"` // RFC3339 date "2026-03-24"
	Citations []string `json:"citations" yaml:"citations"`                   // ≥1 required when status != unknown
}

// Cycle is one release line of an add-on, e.g. Istio "1.31".
type Cycle struct {
	Cycle     string    `json:"cycle" yaml:"cycle"` // leading components of the app version: "1.31"
	EOL       *CycleEOL `json:"eol" yaml:"eol"`     // required
	K8sMin    string    `json:"k8s_min,omitempty" yaml:"k8s_min,omitempty"`
	K8sMax    string    `json:"k8s_max,omitempty" yaml:"k8s_max,omitempty"` // inclusive
	Citations []string  `json:"citations" yaml:"citations"`
}

// CycleEOL is a cycle's end of life as endoflife.date publishes it: a
// "YYYY-MM-DD" date, or a boolean — true means ended on an unpublished date,
// false means no end announced.
type CycleEOL struct {
	Date  string // set when a date is published
	Ended bool   // meaningful only when Date is empty
}

func (e CycleEOL) MarshalJSON() ([]byte, error) {
	if e.Date != "" {
		return json.Marshal(e.Date)
	}
	return json.Marshal(e.Ended)
}

func (e *CycleEOL) UnmarshalJSON(b []byte) error {
	var ended bool
	if err := json.Unmarshal(b, &ended); err == nil {
		*e = CycleEOL{Ended: ended}
		return nil
	}
	var date string
	if err := json.Unmarshal(b, &date); err != nil {
		return fmt.Errorf("eol must be a YYYY-MM-DD date, true or false, got %s", b)
	}
	*e = CycleEOL{Date: date}
	return nil
}

// Compat maps an app version range to a supported K8s range. At least one
// bound is required; a missing bound is open.
type Compat struct {
	Range     string   `json:"range" yaml:"range"`                         // semver constraint, e.g. ">=4.0.0"
	K8sMin    string   `json:"k8s_min,omitempty" yaml:"k8s_min,omitempty"` // "1.21"
	K8sMax    string   `json:"k8s_max,omitempty" yaml:"k8s_max,omitempty"` // "1.36" (inclusive)
	Citations []string `json:"citations" yaml:"citations"`
}
