// registry/types.go
package registry

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
)

// AddOn is one entry in the add-on EOL/compatibility registry (schema_version 2).
type AddOn struct {
	SchemaVersion int      `json:"schema_version" yaml:"schema_version"` // 2
	ID            string   `json:"id" yaml:"id"`
	DisplayName   string   `json:"display_name" yaml:"display_name"`
	Matchers      Matchers `json:"matchers" yaml:"matchers"`
	// Support is the product-level verdict. status "eol" is reserved for a
	// whole product that upstream retired (ingress-nginx); per-version end of
	// life lives in Cycles.
	Support Support `json:"support" yaml:"support"`
	// Cycles are the add-on's release lines, keyed on the APP version (never
	// a Helm chart version), newest first. Entries with endoflife_product
	// have them generated by tools/eol-sync.
	Cycles         []Cycle  `json:"cycles,omitempty" yaml:"cycles,omitempty"`
	Compat         []Compat `json:"compat,omitempty" yaml:"compat,omitempty"`
	Recommendation string   `json:"recommendation,omitempty" yaml:"recommendation,omitempty"`

	// EndoflifeProduct, when set, is the endoflife.date product slug for
	// this add-on (https://endoflife.date/api/<slug>.json). Entries that
	// carry it have Cycles kept in sync by tools/eol-sync; hand-curated
	// entries leave it empty.
	EndoflifeProduct string `json:"endoflife_product,omitempty" yaml:"endoflife_product,omitempty"`
}

type Matchers struct {
	// Images are repository paths without the registry host, matched as a
	// suffix on whole path segments: "ingress-nginx/controller" matches
	// registry.k8s.io/ingress-nginx/controller, k8s.gcr.io/ingress-nginx/controller
	// and mirror/ingress-nginx/controller. The version is read from the tag.
	// They never match a provider build (ProviderBuildPrefixes); an entry
	// for one names it with its host instead. A matcher may end in a tag
	// pattern ("rancher/nginx-ingress-controller:*-hardened*", see
	// SplitTagPattern): it then claims only the tags the pattern matches,
	// ahead of another entry's path-only matcher of that repository.
	Images []string `json:"images,omitempty" yaml:"images,omitempty"`
	Charts []string `json:"charts,omitempty" yaml:"charts,omitempty"` // exact chart name; version = the release's appVersion
	// Runtimes are node container runtime names, the scheme of
	// node.status.nodeInfo.containerRuntimeVersion ("containerd" in
	// "containerd://1.7.27").
	Runtimes []string `json:"runtimes,omitempty" yaml:"runtimes,omitempty"`
	// Components are images of the product's parts that carry their own
	// version, not the product's (Flux's controllers): each maps its
	// release lines to the product release line that ships them.
	Components []ComponentImage `json:"components,omitempty" yaml:"components,omitempty"`
}

type Support struct {
	Status  string `json:"status" yaml:"status"`                         // "supported" | "eol" | "unknown"
	EOLDate string `json:"eol_date,omitempty" yaml:"eol_date,omitempty"` // RFC3339 date "2026-03-24"
	// ExtendedEOLDate and ExtendedSupportCondition describe split support:
	// support ends for everyone on EOLDate and continues until
	// ExtendedEOLDate only if ExtendedSupportCondition holds (a bare clause
	// completing "only if ...", such as a vendor subscription), which the
	// collector cannot see. Both or neither; they need EOLDate and status
	// supported.
	ExtendedEOLDate          string   `json:"extended_eol_date,omitempty" yaml:"extended_eol_date,omitempty"`
	ExtendedSupportCondition string   `json:"extended_support_condition,omitempty" yaml:"extended_support_condition,omitempty"`
	Citations                []string `json:"citations" yaml:"citations"` // ≥1 required when status != unknown
}

// ComponentImage is an image of one part of a product that is versioned
// on its own: Flux's source-controller v1.5 ships in Flux 2.5, its
// helm-controller v1.2 too. The image's release line (major.minor of the
// tag) is mapped to the product's through Lines; a line Lines does not
// list gives no version, never a guess.
type ComponentImage struct {
	Image     string          `json:"image" yaml:"image"` // a path-only image matcher
	Lines     []ComponentLine `json:"lines" yaml:"lines"`
	Citations []string        `json:"citations" yaml:"citations"` // where the mapping is published
}

// ComponentLine maps one release line of a component image to the product
// release line that ships it.
type ComponentLine struct {
	Component string `json:"component" yaml:"component"` // MAJOR.MINOR of the image tag
	Product   string `json:"product" yaml:"product"`     // the product's release line
}

// UnmarshalJSON decodes a line strictly, for the reason Cycle does: an
// unquoted 1.10 would otherwise be read as "1.1", another release line.
func (l *ComponentLine) UnmarshalJSON(b []byte) error {
	type plain ComponentLine
	var p plain
	dec := json.NewDecoder(bytes.NewReader(b))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&p); err != nil {
		var typeErr *json.UnmarshalTypeError
		if errors.As(err, &typeErr) && typeErr.Value == "number" {
			return fmt.Errorf("component line field %q: quote versions (\"1.10\", not 1.10)", typeErr.Field)
		}
		return err
	}
	*l = ComponentLine(p)
	return nil
}

// ProductLine returns the product release line that ships version, a
// version read from the component image's tag ("1.2.0" → "2.5"), or ""
// when Lines does not list its line.
func (c ComponentImage) ProductLine(version string) string {
	major, rest, ok := strings.Cut(version, ".")
	if !ok || major == "" {
		return ""
	}
	minor, _, _ := strings.Cut(rest, ".")
	minor, _, _ = strings.Cut(minor, "-")
	for _, l := range c.Lines {
		if l.Component == major+"."+minor {
			return l.Product
		}
	}
	return ""
}

// Cycle is one release line of an add-on, e.g. Istio "1.31".
type Cycle struct {
	Cycle     string    `json:"cycle" yaml:"cycle"` // leading components of the app version: "1.31"
	EOL       *CycleEOL `json:"eol" yaml:"eol"`     // required
	K8sMin    string    `json:"k8s_min,omitempty" yaml:"k8s_min,omitempty"`
	K8sMax    string    `json:"k8s_max,omitempty" yaml:"k8s_max,omitempty"` // inclusive
	Citations []string  `json:"citations" yaml:"citations"`
}

// UnmarshalJSON decodes a cycle strictly. Being a json.Unmarshaler also
// stops sigs.k8s.io/yaml from coercing unquoted numbers into the string
// fields, which reads `cycle: 1.10` as "1.1" (another release line) and
// `k8s_max: 1.30` as "1.3"; an unquoted version now fails the load.
func (c *Cycle) UnmarshalJSON(b []byte) error {
	type plain Cycle
	var p plain
	dec := json.NewDecoder(bytes.NewReader(b))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&p); err != nil {
		var typeErr *json.UnmarshalTypeError
		if errors.As(err, &typeErr) && typeErr.Value == "number" {
			return fmt.Errorf("cycle field %q: quote versions (\"1.10\", not 1.10)", typeErr.Field)
		}
		return err
	}
	*c = Cycle(p)
	return nil
}

// CycleEOL is a cycle's end of life as endoflife.date publishes it: a
// "YYYY-MM-DD" date, or a boolean — true means ended on an unpublished date,
// false means no end announced.
type CycleEOL struct {
	Date  string // set when a date is published
	Ended bool   // meaningful only when Date is empty
}

func (e CycleEOL) MarshalJSON() ([]byte, error) {
	if e.Date != "" {
		return json.Marshal(e.Date)
	}
	return json.Marshal(e.Ended)
}

func (e *CycleEOL) UnmarshalJSON(b []byte) error {
	var ended bool
	if err := json.Unmarshal(b, &ended); err == nil {
		*e = CycleEOL{Ended: ended}
		return nil
	}
	var date string
	if err := json.Unmarshal(b, &date); err != nil || date == "" {
		return fmt.Errorf("eol must be a YYYY-MM-DD date, true or false, got %s", b)
	}
	*e = CycleEOL{Date: date}
	return nil
}

// Compat maps an app version range to a supported K8s range. At least one
// bound is required; a missing bound is open.
type Compat struct {
	Range     string   `json:"range" yaml:"range"`                         // semver constraint, e.g. ">=4.0.0"
	K8sMin    string   `json:"k8s_min,omitempty" yaml:"k8s_min,omitempty"` // "1.21"
	K8sMax    string   `json:"k8s_max,omitempty" yaml:"k8s_max,omitempty"` // "1.36" (inclusive)
	Citations []string `json:"citations" yaml:"citations"`
}
