package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestAlias(t *testing.T) {
	cases := map[string]string{
		"k8s.io/api/core/v1":                                       "corev1",
		"k8s.io/api/admissionregistration/v1alpha1":                "admissionregistrationv1alpha1",
		"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1": "apiextensionsv1",
		"k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1":  "apiregistrationv1beta1",
		"example.com/x/some-group/v2":                              "somegroupv2",
	}
	for in, want := range cases {
		if got := alias(in); got != want {
			t.Errorf("alias(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestIsGroupVersion(t *testing.T) {
	for _, p := range []string{"k8s.io/api/core/v1", "k8s.io/api/apps/v1beta2", "k8s.io/api/resource/v1alpha3", "k8s.io/api/apidiscovery/v2"} {
		if !isGroupVersion(p) {
			t.Errorf("isGroupVersion(%q) = false, want true", p)
		}
	}
	for _, p := range []string{"k8s.io/api", "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions", "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/install", "k8s.io/api/core/v1/validation"} {
		if isGroupVersion(p) {
			t.Errorf("isGroupVersion(%q) = true, want false", p)
		}
	}
}

func TestExportsAddToScheme(t *testing.T) {
	dir := t.TempDir()
	write := func(name, src string) {
		t.Helper()
		if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("var.go", "package v1\n\nvar (\n\tSchemeBuilder = 1\n\tAddToScheme = 2\n)\n")
	write("func.go", "package v1\n\nfunc AddToScheme() error { return nil }\n")
	write("method.go", "package v1\n\ntype T struct{}\n\nfunc (T) AddToScheme() error { return nil }\n")
	write("none.go", "package v1\n\nvar addToScheme = 1\n")

	cases := []struct {
		files []string
		want  bool
	}{
		{[]string{"var.go"}, true},
		{[]string{"func.go"}, true},
		{[]string{"method.go"}, false}, // a method is not a package-level AddToScheme
		{[]string{"none.go"}, false},   // unexported
		{[]string{"none.go", "var.go"}, true},
	}
	for _, c := range cases {
		got, err := exportsAddToScheme(dir, c.files)
		if err != nil {
			t.Fatalf("exportsAddToScheme(%v) error = %v", c.files, err)
		}
		if got != c.want {
			t.Errorf("exportsAddToScheme(%v) = %v, want %v", c.files, got, c.want)
		}
	}
}

func TestRender(t *testing.T) {
	src, err := render([]string{"k8s.io/api/core/v1", "k8s.io/api/apps/v1"})
	if err != nil {
		t.Fatalf("render() error = %v", err)
	}
	got := string(src)
	for _, want := range []string{
		"// Code generated by internal/genimports; DO NOT EDIT.",
		"package main",
		`appsv1 "k8s.io/api/apps/v1"`,
		`corev1 "k8s.io/api/core/v1"`,
		`"k8s.io/apimachinery/pkg/runtime"`,
		"var addToSchemes = []func(*runtime.Scheme) error{",
		"\tappsv1.AddToScheme,\n\tcorev1.AddToScheme,\n",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("render() output missing %q:\n%s", want, got)
		}
	}

	// Two packages that would share an alias must fail loudly rather than
	// emit a file that does not compile.
	if _, err := render([]string{"a.io/x/core/v1", "b.io/y/core/v1"}); err == nil {
		t.Error("render(colliding aliases) = nil error, want error")
	}
	if _, err := render(nil); err == nil {
		t.Error("render(no packages) = nil error, want error")
	}
}
