package main

// The docs site's generated references (docs/reference): the CLI pages, the
// ClusterReadiness CRD and the REST API, each rendered from the source the
// binary itself uses, so a flag, field or route cannot change without its
// page changing too. TestReferenceIsFresh fails when the committed pages
// differ from what this writes; `make docs-gen` rewrites them.

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/spf13/cobra/doc"
	"go.yaml.in/yaml/v3"

	"github.com/abd-ulbasit/upgradescope/internal/cli"
	"github.com/abd-ulbasit/upgradescope/internal/crd"
)

// genReference replaces <dir>/cli and writes <dir>/crd.md and, from the
// OpenAPI document at openapiPath, <dir>/api.md.
func genReference(dir, openapiPath string) error {
	cliDir := filepath.Join(dir, "cli")
	if err := os.RemoveAll(cliDir); err != nil {
		return err
	}
	if err := os.MkdirAll(cliDir, 0o755); err != nil {
		return err
	}
	if err := genCLIMarkdown(cliDir); err != nil {
		return err
	}
	crdMD, err := genCRDMarkdown(crd.Manifest)
	if err != nil {
		return fmt.Errorf("crd reference: %w", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "crd.md"), crdMD, 0o644); err != nil {
		return err
	}
	spec, err := os.ReadFile(openapiPath)
	if err != nil {
		return err
	}
	apiMD, err := genAPIMarkdown(spec)
	if err != nil {
		return fmt.Errorf("%s: %w", openapiPath, err)
	}
	return os.WriteFile(filepath.Join(dir, "api.md"), append(apiMD, '\n'), 0o644)
}

// genCLIMarkdown writes one page per available command (cobra skips help
// and hidden commands), named and cross-linked as doc.GenMarkdownTree
// names them: upgradescope_tokens_create.md.
func genCLIMarkdown(dir string) error {
	root := cli.Root()
	root.InitDefaultCompletionCmd()
	root.DisableAutoGenTag = true
	return doc.GenMarkdownTree(root, dir)
}

// crdSchema is the part of an OpenAPI v3 schema the CRD reference renders.
// Properties keep their manifest order.
type crdSchema struct {
	Type                 string        `yaml:"type"`
	Format               string        `yaml:"format"`
	Description          string        `yaml:"description"`
	Pattern              string        `yaml:"pattern"`
	Enum                 []string      `yaml:"enum"`
	Required             []string      `yaml:"required"`
	MinLength            *int64        `yaml:"minLength"`
	MaxLength            *int64        `yaml:"maxLength"`
	MaxItems             *int64        `yaml:"maxItems"`
	Minimum              *int64        `yaml:"minimum"`
	Items                *crdSchema    `yaml:"items"`
	AdditionalProperties *crdSchema    `yaml:"additionalProperties"`
	Properties           orderedFields `yaml:"properties"`
}

type orderedField struct {
	Name   string
	Schema *crdSchema
}

type orderedFields []orderedField

func (o *orderedFields) UnmarshalYAML(n *yaml.Node) error {
	if n.Kind != yaml.MappingNode {
		return fmt.Errorf("line %d: properties is not a mapping", n.Line)
	}
	for i := 0; i+1 < len(n.Content); i += 2 {
		var s crdSchema
		if err := n.Content[i+1].Decode(&s); err != nil {
			return err
		}
		*o = append(*o, orderedField{Name: n.Content[i].Value, Schema: &s})
	}
	return nil
}

type crdManifest struct {
	Spec struct {
		Group string `yaml:"group"`
		Scope string `yaml:"scope"`
		Names struct {
			Kind       string   `yaml:"kind"`
			Plural     string   `yaml:"plural"`
			Singular   string   `yaml:"singular"`
			ShortNames []string `yaml:"shortNames"`
			Categories []string `yaml:"categories"`
		} `yaml:"names"`
		Versions []struct {
			Name          string `yaml:"name"`
			Served        bool   `yaml:"served"`
			Storage       bool   `yaml:"storage"`
			PrinterColumn []struct {
				Name        string `yaml:"name"`
				Type        string `yaml:"type"`
				JSONPath    string `yaml:"jsonPath"`
				Description string `yaml:"description"`
			} `yaml:"additionalPrinterColumns"`
			Schema struct {
				OpenAPIV3Schema crdSchema `yaml:"openAPIV3Schema"`
			} `yaml:"schema"`
		} `yaml:"versions"`
	} `yaml:"spec"`
}

// genCRDMarkdown renders a CRD manifest: identity, printer columns, and
// one table row per schema field of every served version.
func genCRDMarkdown(manifest []byte) ([]byte, error) {
	var m crdManifest
	if err := yaml.Unmarshal(manifest, &m); err != nil {
		return nil, err
	}
	s := m.Spec
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n", s.Names.Kind)
	b.WriteString("<!-- Generated by tools/gen-docs from internal/crd/manifest.yaml (make docs-gen). Do not edit. -->\n\n")
	fmt.Fprintf(&b, "The `%s` custom resource, as the agent's embedded CRD manifest defines it. ", s.Names.Kind)
	b.WriteString("The chart installs the same manifest from `deploy/chart/crds/`. ")
	b.WriteString("To turn the verdict into a policy that pushes back, see [Acting on readiness](../guides/acting-on-readiness.md).\n\n")
	b.WriteString("| | |\n|---|---|\n")
	var versions []string
	for _, v := range s.Versions {
		versions = append(versions, fmt.Sprintf("`%s/%s`", s.Group, v.Name))
	}
	fmt.Fprintf(&b, "| API version | %s |\n", strings.Join(versions, ", "))
	fmt.Fprintf(&b, "| Kind | `%s` |\n", s.Names.Kind)
	fmt.Fprintf(&b, "| Scope | %s |\n", s.Scope)
	fmt.Fprintf(&b, "| Plural / singular | `%s` / `%s` |\n", s.Names.Plural, s.Names.Singular)
	if len(s.Names.ShortNames) > 0 {
		fmt.Fprintf(&b, "| Short names | %s |\n", codeList(s.Names.ShortNames))
	}
	if len(s.Names.Categories) > 0 {
		fmt.Fprintf(&b, "| Categories | %s |\n", codeList(s.Names.Categories))
	}
	for _, v := range s.Versions {
		fmt.Fprintf(&b, "\n## %s\n\n", v.Name)
		fmt.Fprintf(&b, "Served: %t. Storage version: %t.\n", v.Served, v.Storage)
		if len(v.PrinterColumn) > 0 {
			b.WriteString("\n### `kubectl get` columns\n\n")
			b.WriteString("| Column | Type | JSONPath | Description |\n|---|---|---|---|\n")
			for _, c := range v.PrinterColumn {
				fmt.Fprintf(&b, "| %s | %s | `%s` | %s |\n", c.Name, c.Type, c.JSONPath, cell(c.Description))
			}
		}
		b.WriteString("\n### Fields\n\n")
		b.WriteString("| Field | Type | Description | Validation |\n|---|---|---|---|\n")
		root := v.Schema.OpenAPIV3Schema
		for _, f := range root.Properties {
			writeFieldRows(&b, f.Name, f.Schema, slices.Contains(root.Required, f.Name))
		}
	}
	return b.Bytes(), nil
}

// writeFieldRows writes path's row, then its properties' and items' rows.
func writeFieldRows(b *bytes.Buffer, path string, s *crdSchema, required bool) {
	fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", path, schemaType(s), cell(s.Description), validation(s, required))
	for _, f := range s.Properties {
		writeFieldRows(b, path+"."+f.Name, f.Schema, slices.Contains(s.Required, f.Name))
	}
	if s.Items != nil {
		writeFieldRows(b, path+"[]", s.Items, false)
	}
}

func schemaType(s *crdSchema) string {
	if s.Type == "object" && s.AdditionalProperties != nil && len(s.Properties) == 0 {
		return "map of " + s.AdditionalProperties.Type
	}
	return s.Type
}

func validation(s *crdSchema, required bool) string {
	var v []string
	if required {
		v = append(v, "required")
	}
	if s.Format != "" {
		v = append(v, "format "+s.Format)
	}
	if s.Pattern != "" {
		v = append(v, "pattern `"+s.Pattern+"`")
	}
	if len(s.Enum) > 0 {
		v = append(v, "one of "+codeList(s.Enum))
	}
	if s.MinLength != nil {
		v = append(v, fmt.Sprintf("min length %d", *s.MinLength))
	}
	if s.MaxLength != nil {
		v = append(v, fmt.Sprintf("max length %d", *s.MaxLength))
	}
	if s.Minimum != nil {
		v = append(v, fmt.Sprintf("minimum %d", *s.Minimum))
	}
	if s.MaxItems != nil {
		v = append(v, fmt.Sprintf("at most %d items", *s.MaxItems))
	}
	return cell(strings.Join(v, "; "))
}

// cell makes s safe for one Markdown table cell: one line, pipes escaped,
// and an em dash for nothing.
func cell(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	if s == "" {
		return "—"
	}
	return strings.ReplaceAll(s, "|", `\|`)
}

func codeList(ss []string) string {
	q := make([]string, len(ss))
	for i, s := range ss {
		q[i] = "`" + s + "`"
	}
	return strings.Join(q, ", ")
}
