package kb

import (
	"os"
	"testing"

	"github.com/abd-ulbasit/upgradescope/internal/inventory"
)

// TestLifecycleDatasetIsGeneratedOnly: the API lifecycle dataset is the
// generated file and nothing else. A hand-written overlay (the former
// supplement.json) had no per-entry citations, nothing enforcing them, and
// shrank to four entries the generator covers since it records deleted
// types; hand-written lifecycle facts belong in tools/gen-kb's fixups, each
// cited and tested there (#166).
func TestLifecycleDatasetIsGeneratedOnly(t *testing.T) {
	files, err := os.ReadDir("data")
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range files {
		if f.Name() == ".DS_Store" { // macOS Finder litter, as registry/load_test.go allows
			continue
		}
		// volumeplugins.json is another dataset, of in-tree volume plugins
		// (#351): hand-authored, every entry cited and checked by
		// TestVolumePluginsData. It holds no API lifecycle fact.
		if f.Name() != "apilifecycle.json" && f.Name() != "volumeplugins.json" {
			t.Errorf("internal/kb/data/%s: the lifecycle dataset is generated by tools/gen-kb alone; put a fact it cannot derive in tools/gen-kb/fixups.go with a citation", f.Name())
		}
	}
}

// TestDeprecationGuideDeletedTypes pins the removals the deprecation guide
// documents for types current k8s.io/api no longer has (it deleted them
// long ago), end-to-end via Load(). tools/gen-kb records them from the
// k8s.io/api releases since v0.17 and the generator's tombstones.
func TestDeprecationGuideDeletedTypes(t *testing.T) {
	k, err := Load()
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}
	idx := NewIndex(k.APILifecycle)

	psp, ok := idx.Lookup("policy", "v1beta1", "PodSecurityPolicy")
	if !ok {
		t.Fatal("Load() missing policy/v1beta1 PodSecurityPolicy")
	}
	if psp.Removed == nil || *psp.Removed != (inventory.Version{Major: 1, Minor: 25}) {
		t.Errorf("PSP Removed = %v, want 1.25", psp.Removed)
	}
	if psp.Replacement != nil {
		t.Errorf("PSP Replacement = %v, want nil (Pod Security Admission is not an API)", psp.Replacement)
	}
	ext, ok := idx.Lookup("extensions", "v1beta1", "PodSecurityPolicy")
	if !ok {
		t.Fatal("Load() missing extensions/v1beta1 PodSecurityPolicy")
	}
	if ext.Removed == nil || *ext.Removed != (inventory.Version{Major: 1, Minor: 16}) {
		t.Errorf("extensions PSP Removed = %v, want 1.16", ext.Removed)
	}

	cases := []struct {
		version string
		removed inventory.Version
	}{
		{"v2beta1", inventory.Version{Major: 1, Minor: 25}},
		{"v2beta2", inventory.Version{Major: 1, Minor: 26}},
	}
	for _, c := range cases {
		e, ok := idx.Lookup("autoscaling", c.version, "HorizontalPodAutoscaler")
		if !ok {
			t.Errorf("Load() missing autoscaling/%s HorizontalPodAutoscaler", c.version)
			continue
		}
		if e.Removed == nil || *e.Removed != c.removed {
			t.Errorf("HPA %s: Removed = %v, want %v", c.version, e.Removed, c.removed)
		}
		if e.Replacement == nil || e.Replacement.Group != "autoscaling" || e.Replacement.Version != "v2" {
			t.Errorf("HPA %s: Replacement = %v, want autoscaling/v2", c.version, e.Replacement)
		}
	}
}
